USE Other;

GO

DROP TABLE IF EXISTS dbo.JSONFileImport

GO

CREATE TABLE dbo.JSONFileImport (
	ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,DBInsertDate DATETIME NULL DEFAULT GETDATE()
	,Name nvarchar(255) NULL
	,Date DATETIME NULL
	,Size FLOAT NULL
	,Contents NVARCHAR(MAX) NULL
)
